### ISSUE TITLE
Define an Optimal Backend Folder Structure

### ISSUE THREAD

**Issue by joystacktrek** [Jeco99/BAS-project#49]
To ensure consistency, readability, and scalability in our backend codebase, we need to establish a well-defined folder structure for our Node.js, Express, and PostgreSQL project.

Proposed Folder Structure:

backend/
controllers/: Contains route handling logic.
models/: Houses database schema definitions and data manipulation logic.
middlewares/: Stores custom middleware functions.
routes/: Defines route handlers and their configurations.
services/: Implements business logic and interfaces with models.
utils/: Holds utility functions and helper modules.
config/: Stores configuration settings, environment variables, and database connection setup.

or [Another Project Structure Sample](https://docs.google.com/document/d/1OpmALWiC9hfOQrC4CwN6szEuAqc3Bu6VG5x9QckOCPU/edit?usp=sharing)

Action Items:

- [x] Create necessary folders mentioned above
- [x] Move your database config inside the folder (db.js) to config/database.js
- [x] Follow and play around sample code provided in the docs.

**Comment by Jeco99** [comment]
done @joystacktrek .
